# Generated by Django 3.2.6 on 2021-08-11 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=6, verbose_name='URL Token')),
                ('url', models.TextField(db_column='url', help_text='This is actual URL', verbose_name='Long URL')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, verbose_name='Created Date')),
            ],
            options={
                'verbose_name_plural': 'Url Detail',
                'db_table': 'UrlDetail',
            },
        ),
    ]
